// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh0moosz7UlVS_tYTM6BnJRebOPAD8TUI',
    appId: '1:315060067666:web:a962633446dbafbd67ee8b',
    messagingSenderId: '315060067666',
    projectId: 'myfisrtapp-jc-1450',
    authDomain: 'myfisrtapp-jc-1450.firebaseapp.com',
    storageBucket: 'myfisrtapp-jc-1450.appspot.com',
    measurementId: 'G-ZKL1528YT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQwW-Qge78R0nRbUutZWYGx_rARmn244k',
    appId: '1:315060067666:android:f330b5dba227ac4567ee8b',
    messagingSenderId: '315060067666',
    projectId: 'myfisrtapp-jc-1450',
    storageBucket: 'myfisrtapp-jc-1450.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqZZqvCTWkceCeV1LaarxQgNRddkaQ_xs',
    appId: '1:315060067666:ios:d79881094ee6cc4a67ee8b',
    messagingSenderId: '315060067666',
    projectId: 'myfisrtapp-jc-1450',
    storageBucket: 'myfisrtapp-jc-1450.appspot.com',
    iosBundleId: 'com.josh.firstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqZZqvCTWkceCeV1LaarxQgNRddkaQ_xs',
    appId: '1:315060067666:ios:d79881094ee6cc4a67ee8b',
    messagingSenderId: '315060067666',
    projectId: 'myfisrtapp-jc-1450',
    storageBucket: 'myfisrtapp-jc-1450.appspot.com',
    iosBundleId: 'com.josh.firstapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh0moosz7UlVS_tYTM6BnJRebOPAD8TUI',
    appId: '1:315060067666:web:b1e83ab34ad1088a67ee8b',
    messagingSenderId: '315060067666',
    projectId: 'myfisrtapp-jc-1450',
    authDomain: 'myfisrtapp-jc-1450.firebaseapp.com',
    storageBucket: 'myfisrtapp-jc-1450.appspot.com',
    measurementId: 'G-9LW2ZWVR0S',
  );
}
